apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmarking
  namespace: benchmarking
  labels:
    app: benchmarking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmarking
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: benchmarking
    spec:
      containers:
        - name: benchmarking
          image: carloscolnaghi/benchmarking:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "5000m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 12
          ports:
            - containerPort: 8080