on:
  release:
    types:
      - released 

name: Build and Push Docker Image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release version
        run: echo "RELEASE_VERSION=$(jq -r '.tag_name' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t carloscolnaghi/benchmarking:${{ env.RELEASE_VERSION }} .

      - name: Push Docker image
        run: docker push carloscolnaghi/benchmarking:${{ env.RELEASE_VERSION }}
